name: Build Ladybird Linux

"on": [workflow_dispatch]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Ladybird
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y autoconf autoconf-archive automake build-essential ccache cmake curl fonts-liberation2 git libdrm-dev libgl1-mesa-dev libtool nasm ninja-build pkg-config python3-venv qt6-base-dev qt6-tools-dev-tools qt6-wayland tar unzip zip libpulse-dev clang lld

      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          echo "$HOME/.cargo/bin" >> "$GITHUB_PATH"

      - name: Build Ladybird
        run: |
          BUILD_PRESET=Release ./Meta/ladybird.py build --gui=Qt

      - name: Pack build
        run: |
          tar -czf ladybird-linux-build.tar.gz Build/release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ladybird-linux-build
          path: ladybird-linux-build.tar.gz
